apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-processor
  template:
    metadata:
      labels:
        app: text-processor
    spec:
      containers:
      - name: text-processor
        image: your-docker-image
        ports:
        - containerPort: 80
